#!/bin/sh

echo "  ░ ░░░ ░░░░░░░░░░░░"
echo "░░░ ░ ░░ ░$(tput setaf 0)████████$(tput sgr 0)░░░"
echo " ░ ░░ ░░$(tput setaf 0)███$(tput setaf 7)██$(tput setaf 1)▓▓▓▓$(tput setaf 0)███$(tput sgr 0)░░"
echo "  ░░ ░░░$(tput setaf 0)█$(tput setaf 7)████$(tput setaf 1)▓▓▓▓$(tput setaf 7)██$(tput setaf 0)█$(tput sgr 0)░░"
echo "░░ ░░░░$(tput setaf 0)█$(tput setaf 7)████$(tput setaf 1)▓▓▓▓▓▓$(tput setaf 7)██$(tput setaf 0)█$(tput sgr 0)░░"
echo "░░░ ░░$(tput setaf 0)██$(tput setaf 7)███$(tput setaf 1)▓▓$(tput setaf 7)████$(tput setaf 1)▓▓$(tput setaf 7)█$(tput setaf 0)██$(tput sgr 0)░░"
echo " ░░░░░$(tput setaf 0)█$(tput setaf 1)▓▓▓▓▓$(tput setaf 7)██████$(tput setaf 1)▓▓▓$(tput setaf 0)█$(tput sgr 0)░░"
echo "░░░ ░░$(tput setaf 0)█$(tput setaf 1)▓$(tput setaf 7)██$(tput setaf 1)▓▓$(tput setaf 7)██████$(tput setaf 1)▓▓▓$(tput setaf 0)█$(tput sgr 0)░░"
echo "   ░░░$(tput setaf 0)█$(tput setaf 7)████$(tput setaf 1)▓$(tput setaf 7)██████$(tput setaf 1)▓▓$(tput setaf 7)█$(tput setaf 0)█$(tput sgr 0)░"
echo "░░ ░ ░$(tput setaf 0)█$(tput setaf 7)████$(tput setaf 1)▓▓$(tput setaf 7)████$(tput setaf 1)▓▓$(tput setaf 7)██$(tput setaf 0)█$(tput sgr 0)░░"
echo " ░░ ░░$(tput setaf 0)█$(tput setaf 1)▓$(tput setaf 7)██$(tput setaf 1)▓▓▓▓▓▓▓▓▓$(tput setaf 7)██$(tput setaf 0)█$(tput sgr 0)░"
echo "  ░░░░$(tput setaf 0)█$(tput setaf 1)▓▓▓$(tput setaf 0)████████$(tput setaf 1)▓▓$(tput setaf 7)█$(tput setaf 0)█$(tput sgr 0)░"
echo "░░░░ ░░$(tput setaf 0)███$(tput setaf 7)██$(tput setaf 0)█$(tput setaf 7)██$(tput setaf 0)█$(tput setaf 7)██$(tput setaf 0)███$(tput sgr 0)░░"
echo " ░ ░░ ░░$(tput setaf 0)█$(tput setaf 7)███$(tput setaf 0)█$(tput setaf 7)██$(tput setaf 0)█$(tput setaf 7)███$(tput setaf 0)█$(tput sgr 0)░░"
echo "░ ░░ ░░░$(tput setaf 0)█$(tput setaf 7)██████████$(tput setaf 0)█$(tput sgr 0)░"
echo " ░░ ░░ ░░$(tput setaf 0)█$(tput setaf 7)████████$(tput setaf 0)█$(tput sgr 0)░░"
echo "  ░░ ░  ░░$(tput setaf 0)████████$(tput sgr 0)░"
